package org.bumo.sdk.core.utils.security;

import java.security.SecureRandom;

/**
 * Random number generation tool class
 *
 * @author bumo
 */
public class RandomUtils{

    public static byte[] generateRandomBytes(int sizeOfRandom){
        return generateRandomBytes(sizeOfRandom, null);
    }

    /**
     * The specified key generated by seed
     * <p>
     * <p>
     * Note: it is important to note that the same seed may generate different random number sequences
     *
     * @param sizeOfRandom The number of random numbers to output; (unit: byte)
     * @param seed         Random seed；
     * @return Random number; the length is equal to the specified value of sizeOfRandom parameter
     */
    public static byte[] generateRandomBytes(int sizeOfRandom, byte[] seed){
        SecureRandom sr = null;
        if (seed == null || seed.length == 0) {
            // 随机；
            sr = new SecureRandom();
        } else {
            sr = new SecureRandom(seed);
        }
        byte[] randomBytes = new byte[sizeOfRandom];
        sr.nextBytes(randomBytes);
        return randomBytes;
    }

}
