package org.bumo.sdk.core.utils.http;

/**
 * HTTP service exception
 * 
 * The exception generated by calling HTTP Service Agent will be wrapped as HttpServiceException
 * 
 * Note: exceptions to the operation method through throws keyword declaration, these exceptions will be thrown out
 * 
 * @author bumo
 *
 */
public class HttpServiceException extends RuntimeException{

	private static final long serialVersionUID = 7316207586307377240L;

	public HttpServiceException() {
	}
	
	public HttpServiceException(String message) {
		super(message);
	}
	
	public HttpServiceException(String message, Throwable cause) {
		super(message, cause);
	}
}
